### ISSUE TITLE
I would like to be able to use your project for my rifle

### ISSUE THREAD

**Issue by longy55** [ByPS128/Arduino-Aliens-M41A-Riffle#1]
@ByPS128  Hello!
I am very interested in your project because I want to add light and sound to my m41a rifle.
I see that you have the arduino files, but I have not seen a wiring diagram for the electronics or the sound files. Is there a way to get them?
I would like to contribute in some way monetarily for all the work you have done if I can use it for myself.

Thanks in advance!

**Comment by ByPS128** [comment]
Hey. Hey,
I'm glad you're interested in the project and that you're also a fan of the
cult movie Aliens ;)
Yes, I have the circuit diagram. I'm currently working on it and trying to
figure out how to wire it all up on the perfboard.

No need to contribute financially, I'm doing this as a bit of a hobby and
to learn new things. Anyway, thanks for the offer ;)

This is the segment display that the software supposes:
https://www.aliexpress.us/item/3256805033000283.html

And this is the used DF Player:
https://www.aliexpress.us/item/3256803321045196.html

**Comment by longy55** [comment]
OK thank you very much for doing it altruistically!

Thanks for the information on the electronic components, what I have searched for on Github are the diagram and the sound files, but it is probably because I have not searched for them well hehe, I am going to look at everything carefully, I don't want to be annoying either.

**Comment by ByPS128** [comment]
I couldn't find any sound files either. So I bought the game "Aliens
Colonial Marines" in which I muted the music and gunfire and recorded,
cleaned and edited the gun sounds in AudaCity (free). I converted them to
8bit mono 22K to get small but still good quality sound files. The size is
crucial for the delay before the sound starts playing.
The sounds that I missed or couldn't get clean I fished in various free
sound banks and then edited again as needed.
It is also essential to use the DriveSort app:
https://www.anerty.net/software/file/DriveSort/

which sorts the files on the SD card so that they are physically organized
in sequence. This also has a major effect on the delay before the sound
starts playing.

The SD card must contain the directory "01" in the root and these files in
it. it's the numbering that's important, the rest of the file name doesn't
matter:

001-Shoot-95.wav
002-Shoot-95.wav
003-Shoot-95.wav
004-Shoot-95.wav
005-Shoot-95.wav
006-Shoot-95.wav
010-Cock-01-Sniper.wav
011-Cock-02.wav
012-Cock-03.wav
013-Cock-04.wav
014-Cock-05.wav
020-Empty.wav
021-Empty.wav
022-Empty.wav
023-Empty.wav
024-Empty.wav
030-MagazineEject-01.wav
031-MagazineEject-02.wav
040-MagazineLoad-01.wav
041-MagazineLoad-02.wav
042-MagazineLoad-03.wav
050-MagazineReload-01.wav
051-MagazineReload-02.wav
053-MagazineReloadCock-01.wav
054-MagazineReloadCock-02.wav
060-GranadeFire-01.wav
061-GranadeFire-02.wav
062-GranadeFire-03.wav
065-GranadeLoad-01.wav
066-GranadeExplosion-01.wav
067-GranadeExplosion-02.wav
070-Volume-01-Down.wav
071-Volume-02-Down.wav
072-Volume-03-Down.wav
073-Volume-04-Down.wav
074-Volume-05-Down.wav
080-Volume-01-Up.wav
081-Volume-02-Up.wav
082-Volume-03-Up.wav
083-Volume-04-Up.wav
084-Volume-05-Up.wav
090-CardInserted.wav
091-CardRemoved.wav
092-LowBattery.wav
093-VolumeSaved.wav
094-WeaponReady.wav
095-Click-01.wav

I have used some sounds in several forms and the application plays them
randomly. So, for example, the sound of pressing a tap with an empty tray
doesn't sound the same and monotonous all the time. Similarly other sounds.
This makes the simulator more attractive. If you had fewer sound files,
their use is defined in AppConstantes.h, for example:
static const int SAMPLE_EMPTY_MAGAZINE_FIRST = 20;
static const int SAMPLE_EMPTY_MAGAZINE_LAST = 24;
a randomly selected file with a number from 20 to 24 is used to play the
empty sound

But some sound files are not used, like WeaponReady, VolumeUp/Down, Card
inserted/removed and LowBattery
Maybe in future with a little bit better sound player.

**Comment by longy55** [comment]
It's incredible work you're doing man. I can't imagine the hours you would have had to spend to get the different sounds.
I'm embarrassed to ask you for those sound files without having made any effort, that's why I didn't mind contributing even if it was to the expense of the Colonial Marines :D

**Comment by ByPS128** [comment]
I wouldn't want to violate anyone's copyright by publishing those sounds. So I'm going to have to disappoint you on this one. However, with a little determination, you can create the sounds. Look for keywords like "magazine load", "cock", etc.  Then you find sounds like this:
https://artlist.io/sfx/track/battle-rifles---fn-fal-cocking-gun/80693
Hope it help.

**Comment by longy55** [comment]
I understand perfectly, thank you very much! I'll try to get the sounds out :)

**Comment by ByPS128** [comment]
I updated the readme, check it out ;)
https://github.com/ByPS128/Arduino-Aliens-M41A-Riffle

**Comment by longy55** [comment]
nice readme! great job, everything is understood perfectly :)
